name: "halt"
description: |
  Halt and un-halt open PRs by committing a file to your repository
author: "Freckle"
inputs:
  default-branch:
    description: "The default branch for the repository"
    required: true
    default: "main"
  halt-branch:
    description: "The branch where the halt file may be found, if not the default-branch"
    required: false
  halt-file:
    description: "The path to the file used to halt"
    require: true
    default: ".github/HALT"
  status-context:
    description: "The context used when commit-statuses are created"
    required: true
    default: "halt"
  status-target-url:
    description: "An optional target-url for commit-statuses"
    required: true
    default: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  slack-webhook:
    description: "Webhook URL to send Slack notifications"
    required: false
  slack-channels:
    description: "Newline-separated channels to send Slack notifications to, if not the webhook default"
    required: false
  github-token:
    description: "Override GitHub token, if necessary"
    required: true
    default: "${{ github.token }}"
runs:
  using: "node20"
  main: "dist/index.js"
