name: Mergeabot

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  pull-request: write
  
jobs:
  mergeabot:
    runs-on: ubuntu-latest
    steps:
      - uses: freckle/mergeabot-action@v1
